#!/usr/bin/env python3
"""Settings-page thumbnails: renders each option with the watch's own compositor (build/host/preview),
encodes it as lossless WebP and writes src/pkjs/thumbs.js (data URIs, so the page needs no hosting).

Usage: tools/host/build.sh && python3 tools/thumbs.py
Needs cwebp (brew install webp). Rerun whenever the look of an option changes; the output is committed.
Two sets: PT2 frames and Round 2 frames (round=1, black outside the circle); the page shows the set for
the watch it is configuring.
"""
import base64
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREVIEW = os.path.join(ROOT, "build", "host", "preview")
RES = os.path.join(ROOT, "resources")
OUT = os.path.join(ROOT, "src", "pkjs", "thumbs.js")

# key: (preview arguments, crop (x, y, size) or None for the whole frame)
BORDER_SCENE = ["1438", "cloudy", "afternoon"]
BORDER_CROP = (120, 136, 64)  # where the 8 meets white cloud and white sky: the rim is what separates them
THUMBS = {
    "bgDay0": (["1008", "partly", "midday", "sun=150,40"], None),
    "bgDay1": (["1008", "partly", "midday", "bg=1"], None),
    "bgNight0": (["2231", "rain", "night", "moon=200"], None),
    "bgNight1": (["2231", "rain", "night", "bg=1"], None),
    "sky0": (["0742", "rain", "morning"], None),
    "sky1": (["0742", "rain", "morning", "solid=1"], None),
    "border0": (BORDER_SCENE + ["border=0"], BORDER_CROP),
    "border1": (BORDER_SCENE + ["border=1"], BORDER_CROP),
}
# Round 2: the same scenes on the round screen (round=1 goes first so sun= is read in Round 2 px)
ROUND_BORDER_CROP = (149, 151, 64)  # the same spot on the 8, moved with the Round 2 layout
ROUND_ARGS = {"bgDay0": ["1008", "partly", "midday", "sun=190,52"]}
ROUND_THUMBS = {k: (ROUND_ARGS.get(k, args), ROUND_BORDER_CROP if crop else None) for k, (args, crop) in THUMBS.items()}


def read_png(path):
    d = open(path, "rb").read()
    i, idat = 8, b""
    while i < len(d):
        n = struct.unpack(">I", d[i:i + 4])[0]
        t, c = d[i + 4:i + 8], d[i + 8:i + 8 + n]
        i += 12 + n
        if t == b"IHDR":
            w, h, depth, ctype = struct.unpack(">IIBB", c[:10])
            if depth != 8 or ctype != 2:
                sys.exit(f"{path}: expected 8-bit RGB from the preview tool")
        elif t == b"IDAT":
            idat += c
    raw, stride = zlib.decompress(idat), w * 3
    rows = []
    for y in range(h):
        if raw[y * (stride + 1)] != 0:
            sys.exit(f"{path}: expected unfiltered rows from the preview tool")
        rows.append(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
    return w, h, rows


def write_png(path, w, h, rows):
    chunk = lambda t, c: struct.pack(">I", len(c)) + t + c + struct.pack(">I", zlib.crc32(t + c) & 0xFFFFFFFF)
    raw = b"".join(b"\0" + r for r in rows)
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) +
                chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def main():
    if not os.path.exists(PREVIEW):
        sys.exit("build the host tools first: tools/host/build.sh")
    if not shutil.which("cwebp"):
        sys.exit("cwebp not found (brew install webp)")
    out = {"pt2": {}, "round": {}}
    with tempfile.TemporaryDirectory() as tmp:
        for kind, key, (args, crop) in [("pt2", k, v) for k, v in THUMBS.items()] + \
                                          [("round", k, v) for k, v in ROUND_THUMBS.items()]:
            png = os.path.join(tmp, kind + key + ".png")
            head = args[:3] + (["round=1"] if kind == "round" else [])
            subprocess.run([PREVIEW, RES, png] + head + args[3:], check=True)
            if crop:
                x0, y0, s = crop
                w, h, rows = read_png(png)
                if x0 < 0 or y0 < 0 or x0 + s > w or y0 + s > h:
                    sys.exit(f"{key}: crop {crop} falls outside the {w} x {h} frame")
                write_png(png, s, s, [r[x0 * 3:(x0 + s) * 3] for r in rows[y0:y0 + s]])
            webp = os.path.join(tmp, kind + key + ".webp")
            subprocess.run(["cwebp", "-quiet", "-lossless", "-z", "9", png, "-o", webp], check=True)
            out[kind][key] = base64.b64encode(open(webp, "rb").read()).decode()
    lines = ["// Generated by tools/thumbs.py from the watch's own renderer: do not edit.",
             "// Settings-page option thumbnails, lossless WebP: full frames (PT2 200 x 228, Round 2 260 x 260 with",
             "// black outside the circle) and 64 x 64 border crops.",
             "'use strict';", "", "module.exports = {"]
    for kind, set_ in out.items():
        lines.append(f"  {kind}: {{")
        lines += [f"    {k}: 'data:image/webp;base64,{v}'," for k, v in set_.items()]
        lines.append("  },")
    lines += ["};", ""]
    open(OUT, "w").write("\n".join(lines))
    for kind, set_ in out.items():
        print(f"{kind}: {len(set_)} thumbnails, {sum(len(v) for v in set_.values())} base64 bytes")


if __name__ == "__main__":
    main()
